#!/usr/bin/env bash
echo "laptop" > $HOME/.screenLayout
xrandr --output eDP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output VGA-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-1-2 --off --output DP-1-3 --off --output DP-1-4 --off &&\
$HOME/Code/dotfiles/scripts/layouts/postswitch
