#!/usr/bin/env bash

SCREEN_CURRENT_PROFILE=$(cat $HOME/.screenLayout)
# reload bspwm and send notification
$HOME/.config/bspwm/bspwmrc > /dev/null 2>&1 && notify-send -i display "Screen" "Switched to $SCREEN_CURRENT_PROFILE profile"
