#!/usr/bin/env bash

###########################
### BSPWM configuration ###
###########################

if xrandr -q | grep 'HDMI1 connected'; then
  bspc monitor HDMI1 -d 1 2 3 4 5
else
  bspc monitor eDP1 -d 1 2 3 4 5
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config click_to_focus true

###################
### BSPWM rules ###
###################

#bspc rule -a Chromium desktop='^2'
#bspc rule -a Microsoft-edge desktop='^2'
#bspc rule -a Code desktop='^4'
bspc rule -a Screenkey manage=off
# launch telegram in floating mode
bspc rule -a TelegramDesktop state=floating floating=on
# launch whatsapp nativifier in floating mode
bspc rule -a whatsapp-nativefier-d40211 state=floating floating=on
# launch sticky notes in floating mode
bspc rule -a MyNotes state=floating floating=on

######################
### BSPWM coloring ###
######################
bspc config presel_feedback_color "#689992"
bspc config normal_border_color "#575268"
bspc config active_border_color "#F5E0DC"
bspc config border_width 1

# autostart
bash $HOME/.config/bspwm/scripts/autostart.sh
