#!/usr/bin/env bash

###########################
### BSPWM configuration ###
###########################

if xrandr -q | grep 'HDMI1 connected'; then
  bspc monitor HDMI1 -d 1 2 3 4 5 6
else
  bspc monitor eDP1 -d 1 2 3 4 5 6
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config window_gap 5

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer false
bspc config click_to_focus true

###################
### BSPWM rules ###
###################

#bspc rule -a Chromium desktop='^2'
#bspc rule -a Microsoft-edge desktop='^2'
#bspc rule -a Code desktop='^4'
bspc rule -a Screenkey manage=off
# launch telegram in floating mode
bspc rule -a TelegramDesktop state=floating floating=on
# launch whatsapp nativifier in floating mode
bspc rule -a whatsapp-nativefier-d40211 state=floating floating=on
# launch network manager applet in floating mode
bspc rule -a Nm-connection-editor state=floating floating=on
# launch feh in floating mode
bspc rule -a feh state=floating floating=on
# launch sound settings in floating mode
bspc rule -a Pavucontrol state=floating floating=on

######################
### BSPWM coloring ###
######################
bspc config presel_feedback_color "#689992"
bspc config normal_border_color "#575268"
bspc config active_border_color "#decec8"
bspc config border_width 1

# autostart scripts

# Enable shortcuts
pgrep -x sxhkd >/dev/null || sxhkd &
# Monitor
#~/.screenlayout/monitor.sh & # disabled due to autorandr taking care
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
if [[ ! $(pidof polkit-gnome-authentication-agent-1) ]]; then
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
picom --experimental-backend -b &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# Low battery notifier
~/Code/dotfiles/scripts/low_bat_notifier.sh &
